AVATAR_COLORS = {
    'jw':  ('qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #3B68F1,stop:1 #1E3FAF)', '#3B68F1'),
    'sh':  ('qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #E11D48,stop:1 #BE123C)', '#E11D48'),
    'mk':  ('qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #10B981,stop:1 #047857)', '#10B981'),
    'yj':  ('qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #F59E0B,stop:1 #B45309)', '#F59E0B'),
    'bot': ('qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #6366F1,stop:1 #4338CA)', '#6366F1'),
    'hr':  ('qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #0EA5E9,stop:1 #0369A1)', '#0EA5E9'),
}

CHANNELS = [
    {'id': 'general',    'name': 'general',       'topic': '팀 전체 공지 · 잡담',           'unread': 0},
    {'id': 'bom-review', 'name': 'bom-review',    'topic': 'BOM 검토 및 승인 요청',          'unread': 3},
    {'id': 'sourcing',   'name': 'parts-sourcing', 'topic': '부품 수급 · 대체품 · 단가 협의', 'unread': 0},
    {'id': 'design',     'name': 'design-review',  'topic': '회로 설계 리뷰',                 'unread': 12},
    {'id': 'random',     'name': 'random',         'topic': '',                               'unread': 0},
]

DMS = [
    {'id': 'dm-sh', 'name': '서현 (PCB)',    'initials': 'SH', 'color': 'sh', 'presence': 'online',  'unread': 1},
    {'id': 'dm-mk', 'name': '민결 (구매)',    'initials': 'MK', 'color': 'mk', 'presence': 'online',  'unread': 0},
    {'id': 'dm-yj', 'name': '윤재 (펌웨어)', 'initials': 'YJ', 'color': 'yj', 'presence': 'away',    'unread': 0},
    {'id': 'dm-hr', 'name': '하린 (QA)',      'initials': 'HR', 'color': 'hr', 'presence': 'offline', 'unread': 0},
]

MESSAGES = [
    # ── general ──────────────────────────────────────────────
    {'id': 'g1', 'day': '오늘', 'channel': 'general',
     'author': '김지운', 'initials': 'JW', 'color': 'jw', 'ts': '오전 9:05',
     'text': '안녕하세요 팀원분들! 오늘 오디오 프리앰프 v2 설계 킥오프입니다. 채널별로 진행하겠습니다.'},
    {'id': 'g2', 'channel': 'general',
     'author': '서현', 'initials': 'SH', 'color': 'sh', 'ts': '오전 9:07',
     'text': '네, 스케줄 확인했습니다. PCB 레이아웃은 BOM 확정 이후 시작할게요.',
     'reactions': [{'emo': '👍', 'count': 3, 'mine': True}]},
    {'id': 'g3', 'channel': 'general',
     'author': '윤재', 'initials': 'YJ', 'color': 'yj', 'ts': '오전 9:10',
     'text': '펌웨어는 I2C 드라이버 먼저 붙여놓겠습니다. 오피앰프 선정 결과 나오면 알려주세요.'},
    {'id': 'g4', 'channel': 'general',
     'author': '하린', 'initials': 'HR', 'color': 'hr', 'ts': '오전 9:12',
     'text': 'QA 쪽은 테스트 케이스 초안 작성 중입니다. 완성되면 #design-review에 올릴게요.',
     'reactions': [{'emo': '✅', 'count': 2, 'mine': False}]},

    # ── bom-review ───────────────────────────────────────────
    {'id': 'm1', 'day': '오늘', 'channel': 'bom-review',
     'author': '김지운', 'initials': 'JW', 'color': 'jw', 'ts': '오전 9:24',
     'text': '오디오 프리앰프 v2 BOM 올렸습니다. 오피앰프 세 후보 단가 비교 부탁드려요.'},
    {'id': 'm2', 'channel': 'bom-review',
     'author': '김지운', 'initials': 'JW', 'color': 'jw', 'ts': '오전 9:24', 'grouped': True,
     'text': 'LM358 / TL072 / NE5532 중에서 노이즈랑 단가 보고 고르면 될 것 같습니다.',
     'file': {'name': 'preamp_v2_BOM.csv', 'meta': 'CSV · 38개 부품 · 12.4 KB'}},
    {'id': 'm3', 'channel': 'bom-review',
     'author': 'CircuitKit', 'initials': 'CK', 'color': 'bot', 'ts': '오전 9:25', 'bot': True,
     'text': '요청하신 3개 부품을 DigiKey에서 조회했습니다. 최저 단가 기준으로 정리했어요.',
     'parts': [{'name': 'NE5532P', 'maker': 'STMicroelectronics', 'digikey': '497-1639-5-ND',
                'price': '$0.404', 'priceUnit': '1,000개 기준', 'package': 'PDIP-8',
                'mount': 'Through Hole', 'status': 'Active', 'stock': '12,340', 'best': True}]},
    {'id': 'm4', 'channel': 'bom-review',
     'author': 'CircuitKit', 'initials': 'CK', 'color': 'bot', 'ts': '오전 9:25', 'grouped': True,
     'parts': [{'name': 'LM358P', 'maker': 'Texas Instruments', 'digikey': '296-1395-5-ND',
                'price': '$0.119', 'priceUnit': '1,000개 기준', 'package': 'PDIP-8',
                'mount': 'Through Hole', 'status': 'Active', 'stock': '47,892', 'cheapest': True}]},
    {'id': 'm4b', 'channel': 'bom-review',
     'author': 'CircuitKit', 'initials': 'CK', 'color': 'bot', 'ts': '오전 9:25', 'grouped': True,
     'parts': [{'name': 'TL072CP', 'maker': 'Texas Instruments', 'digikey': '296-7365-5-ND',
                'price': '$0.276', 'priceUnit': '1,000개 기준', 'package': 'PDIP-8',
                'mount': 'Through Hole', 'status': 'Active', 'stock': '31,120'}]},
    {'id': 'm5', 'channel': 'bom-review',
     'author': '서현', 'initials': 'SH', 'color': 'sh', 'ts': '오전 9:31',
     'text': '단가만 보면 LM358이 압도적인데, 이 보드는 오디오라서 노이즈가 중요해요. NE5532가 정석이긴 합니다.',
     'reactions': [{'emo': '👍', 'count': 3, 'mine': True}, {'emo': '🎧', 'count': 1, 'mine': False}],
     'thread': {'count': 4, 'avatars': [('MK','mk'), ('YJ','yj'), ('JW','jw')], 'last': '5분 전'}},
    {'id': 'm6', 'channel': 'bom-review',
     'author': '민결', 'initials': 'MK', 'color': 'mk', 'ts': '오전 9:38',
     'text': 'NE5532 재고 12,340개면 이번 1차 양산(2,000ea)은 충분합니다. 단가는 제가 대량 견적 한번 더 따볼게요.',
     'parts': [{'name': 'NE5532P', 'maker': 'STMicroelectronics', 'digikey': '497-1639-5-ND',
                'price': '$0.404', 'priceUnit': '1,000개 기준', 'package': 'PDIP-8',
                'mount': 'Through Hole', 'status': 'Active', 'stock': '12,340'}]},
    {'id': 'm7', 'channel': 'bom-review',
     'author': '김지운', 'initials': 'JW', 'color': 'jw', 'ts': '오전 9:42',
     'text': '좋습니다. 그럼 NE5532P로 확정하고 BOM 업데이트할게요. R7, R8 게인 저항만 다시 계산하면 됩니다.',
     'reactions': [{'emo': '✅', 'count': 4, 'mine': True}]},

    # ── parts-sourcing ────────────────────────────────────────
    {'id': 's1', 'day': '오늘', 'channel': 'sourcing',
     'author': '민결', 'initials': 'MK', 'color': 'mk', 'ts': '오전 10:05',
     'text': '디커플링 캡 MLCC 100nF 재고 부족 이슈 있습니다. GRM188R71H104KA93D 대체품 찾아봤어요.'},
    {'id': 's2', 'channel': 'sourcing',
     'author': 'CircuitKit', 'initials': 'CK', 'color': 'bot', 'ts': '오전 10:06', 'bot': True,
     'text': 'GRM188R71H104KA93D 조회 결과입니다. 재고 부족 상태입니다.',
     'parts': [{'name': 'GRM188R71H104KA93D', 'maker': 'Murata', 'digikey': '490-6407-1-ND',
                'price': '$0.018', 'priceUnit': '4,000개 기준', 'package': '0603',
                'mount': 'SMD', 'status': 'Active', 'stock': '180'}]},
    {'id': 's3', 'channel': 'sourcing',
     'author': 'CircuitKit', 'initials': 'CK', 'color': 'bot', 'ts': '오전 10:06', 'grouped': True,
     'text': '대체 가능한 삼성 부품을 추천합니다.',
     'parts': [{'name': 'CL10B104KO8NNNC', 'maker': 'Samsung', 'digikey': '1276-1003-1-ND',
                'price': '$0.010', 'priceUnit': '4,000개 기준', 'package': '0603',
                'mount': 'SMD', 'status': 'Active', 'stock': '284,500', 'best': True}]},
    {'id': 's4', 'channel': 'sourcing',
     'author': '서현', 'initials': 'SH', 'color': 'sh', 'ts': '오전 10:14',
     'text': '삼성꺼 전압 정격 확인했나요? X7R 스펙이 같으면 대체 가능합니다.',
     'reactions': [{'emo': '🔍', 'count': 2, 'mine': False}]},
    {'id': 's5', 'channel': 'sourcing',
     'author': '민결', 'initials': 'MK', 'color': 'mk', 'ts': '오전 10:17',
     'text': '확인했습니다. 50V X7R 동일 스펙입니다. 단가도 절반이라 이걸로 교체할게요.',
     'reactions': [{'emo': '✅', 'count': 3, 'mine': True}]},

    # ── design-review ─────────────────────────────────────────
    {'id': 'd1', 'day': '오늘', 'channel': 'design',
     'author': '하린', 'initials': 'HR', 'color': 'hr', 'ts': '오전 11:00',
     'text': '입력단 바이어스 저항 R3, R4 값이 스펙시트 권장값(10kΩ)보다 낮게 잡혀 있어요. 이유가 있나요?',
     'file': {'name': 'preamp_v2_schematic_review.pdf', 'meta': 'PDF · 회로 리뷰 코멘트 · 2.1 MB'}},
    {'id': 'd2', 'channel': 'design',
     'author': '김지운', 'initials': 'JW', 'color': 'jw', 'ts': '오전 11:08',
     'text': '소스 임피던스 매칭 때문에 일부러 낮췄습니다. 마이크 프리앰프 쪽은 소스 임피던스가 200Ω 이하라서요.',
     'reactions': [{'emo': '💡', 'count': 2, 'mine': False}]},
    {'id': 'd3', 'channel': 'design',
     'author': '하린', 'initials': 'HR', 'color': 'hr', 'ts': '오전 11:12',
     'text': '아, 라인 레벨 인풋이 아니라 마이크 인풋이었군요. 이해했습니다. 코멘트 반영할게요.',
     'reactions': [{'emo': '✅', 'count': 1, 'mine': True}],
     'thread': {'count': 2, 'avatars': [('JW','jw'), ('HR','hr')], 'last': '방금'}},
    {'id': 'd4', 'channel': 'design',
     'author': '윤재', 'initials': 'YJ', 'color': 'yj', 'ts': '오전 11:20',
     'text': 'I2C 풀업 저항 R12, R13도 확인해주세요. 현재 10kΩ인데 400kHz Fast mode면 2.2kΩ 권장입니다.',
     'reactions': [{'emo': '👀', 'count': 2, 'mine': False}]},
    {'id': 'd5', 'channel': 'design',
     'author': 'CircuitKit', 'initials': 'CK', 'color': 'bot', 'ts': '오전 11:21', 'bot': True,
     'text': '풀업 저항 추천 부품 조회했습니다.',
     'parts': [{'name': 'RC0603FR-072K2L', 'maker': 'Yageo', 'digikey': '311-2.20KHRCT-ND',
                'price': '$0.009', 'priceUnit': '5,000개 기준', 'package': '0603',
                'mount': 'SMD', 'status': 'Active', 'stock': '1,240,000', 'best': True}]},
    {'id': 'd6', 'channel': 'design',
     'author': '김지운', 'initials': 'JW', 'color': 'jw', 'ts': '오전 11:25',
     'text': '좋은 지적입니다. R12, R13 2.2kΩ로 수정할게요. BOM도 같이 업데이트하겠습니다.',
     'reactions': [{'emo': '✅', 'count': 4, 'mine': True}, {'emo': '🔧', 'count': 1, 'mine': False}]},
]

SHARE_PARTS = [
    {'name': 'LM358P', 'sub': 'TI · Op Amp Dual', 'price': '$0.27',
     'datasheet_url': 'https://www.ti.com/lit/ds/symlink/lm358.pdf',
     'digikey_url': 'https://www.digikey.com/en/products?keywords=LM358P'},
    {'name': 'TL072CP', 'sub': 'TI · JFET Low Noise', 'price': '$1.04',
     'datasheet_url': 'https://www.ti.com/lit/ds/symlink/tl072.pdf',
     'digikey_url': 'https://www.digikey.com/en/products?keywords=TL072CP'},
    {'name': 'NE5532P', 'sub': 'ST · Audio Op Amp', 'price': '$0.85',
     'datasheet_url': 'https://www.st.com/resource/en/datasheet/ne5532.pdf',
     'digikey_url': 'https://www.digikey.com/en/products?keywords=NE5532P'},
    {'name': 'ESP32-WROOM-32', 'sub': 'Espressif · MCU', 'price': '$3.10',
     'datasheet_url': 'https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf',
     'digikey_url': 'https://www.digikey.com/en/products?keywords=ESP32-WROOM-32'},
]

PRESENCE_COLORS = {'online': '#10B981', 'away': '#F59E0B', 'offline': '#CBD5E1'}
